### ISSUE TITLE
Add App Permissions

### ISSUE THREAD

**Issue by jaydip-pawar** [Google-Developer-Students-Club-DMCE/Women-Safety-App-Hactoberfest-2022#6]
Add permissions in **AndroidManifest.xml** that are required for app to function properly:
Add Following Permissions:

```
ACCESS_COARSE_LOCATION
INTERNET
ACCESS_WIFI_STATE
ACCESS_NETWORK_STATE
READ_CONTACTS
SEND_SMS
ACCESS_FINE_LOCATION
ACCESS_COARSE_LOCATION
```

**Comment by MansiBhayade** [comment]
can you assign this to me ?

**Comment by jaydip-pawar** [comment]
Yes sure, go ahead!

**Comment by axatabyss** [comment]
Can you please assign this issue to me as there is no update from MansiBhayade

Thanks

**Comment by jaydip-pawar** [comment]
> Can you please assign this issue to me as there is no update from MansiBhayade
> 
> Thanks

Ok @axatabyss

**Comment by jaydip-pawar** [comment]
This issue is completed and push request will get merge soon.
